version: "3"
services:
  nexus:
    image: sonatype/nexus3
    ports:
      - "8081:8081"
    container_name: nexus
    restart: always
    volumes:
      - nexus-data:/nexus-data

volumes:
  nexus-data:
