version: "3"

services:
    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.14.1
        container_name: elasticsearch
        ports:
            - 9200:9200
            - 9300:9300
        environment:
            - node.name=es01
            - cluster.name=logging
            - discovery.type=single-node
        volumes:
            - elasticData:/usr/share/elasticsearch/data

    kibana:
        image: docker.elastic.co/kibana/kibana:7.14.1
        container_name: kibana
        ports:
            - 5601:5601
        environment:
            -  "ELASTICSEARCH_HOSTS=http://elasticsearch:9200"
        depends_on: 
            - elasticsearch

volumes:
    elasticData:
